// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/answer_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8162755645001904365),
    name: 'AnswerChunk',
    lastPropertyId: const obx_int.IdUid(7, 7668600048323438331),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6463137983870747339),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 363967556209228140),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2701887692716083341),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 4023350571186130358),
        hnswParams: obx_int.ModelHnswParams(dimensions: 1536),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1408057845629815315),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6698630288509724238),
        name: 'lastUsedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7641218023535385355),
        name: 'confidence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7668600048323438331),
        name: 'sourceQuery',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8162755645001904365),
    lastIndexId: const obx_int.IdUid(1, 4023350571186130358),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AnswerChunk: obx_int.EntityDefinition<AnswerChunk>(
      model: _entities[0],
      toOneRelations: (AnswerChunk object) => [],
      toManyRelations: (AnswerChunk object) => {},
      getId: (AnswerChunk object) => object.id,
      setId: (AnswerChunk object, int id) {
        object.id = id;
      },
      objectToFB: (AnswerChunk object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final sourceQueryOffset = fbb.writeString(object.sourceQuery);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.lastUsedAt.millisecondsSinceEpoch);
        fbb.addFloat64(5, object.confidence);
        fbb.addOffset(6, sourceQueryOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final lastUsedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final confidenceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final sourceQueryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = AnswerChunk(
          text: textParam,
          embedding: embeddingParam,
          createdAt: createdAtParam,
          lastUsedAt: lastUsedAtParam,
          confidence: confidenceParam,
          sourceQuery: sourceQueryParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AnswerChunk] entity fields to define ObjectBox queries.
class AnswerChunk_ {
  /// See [AnswerChunk.id].
  static final id = obx.QueryIntegerProperty<AnswerChunk>(
    _entities[0].properties[0],
  );

  /// See [AnswerChunk.text].
  static final text = obx.QueryStringProperty<AnswerChunk>(
    _entities[0].properties[1],
  );

  /// See [AnswerChunk.embedding].
  static final embedding = obx.QueryHnswProperty<AnswerChunk>(
    _entities[0].properties[2],
  );

  /// See [AnswerChunk.createdAt].
  static final createdAt = obx.QueryDateProperty<AnswerChunk>(
    _entities[0].properties[3],
  );

  /// See [AnswerChunk.lastUsedAt].
  static final lastUsedAt = obx.QueryDateProperty<AnswerChunk>(
    _entities[0].properties[4],
  );

  /// See [AnswerChunk.confidence].
  static final confidence = obx.QueryDoubleProperty<AnswerChunk>(
    _entities[0].properties[5],
  );

  /// See [AnswerChunk.sourceQuery].
  static final sourceQuery = obx.QueryStringProperty<AnswerChunk>(
    _entities[0].properties[6],
  );
}
